# This script reads all of the files in ./train/
# that are saved in our CORL17 format
# and outputs a file that lists all files formatted
# for SegNet
#
###  Input: a subdirectory ./train/ with *.rgb and *.labels files (generated by preceding CORL17 pipeline)
###  Output: a .txt that lists of all *.rgb and *.labels pairs (for SegNet training)

import os
import re

print "Opening the training set descriptor file..."
target = open("train.txt", 'w')

rgb_pattern = re.compile("rgb")
labels_pattern = re.compile("labels")

cwd = os.getcwd()

rgb_match = ""
labels_match = ""


def WritePairToFile(rgb_file_name, labels_file_name):
	target.write(cwd + "/train/" + rgb_file_name)
	target.write(" ")
	target.write(cwd + "/train/" + labels_file_name)
	target.write("\n")


for filename in sorted(os.listdir(cwd + "/train")):

    print filename

    if rgb_pattern.search(filename) is not None:
    	print "found rgb match"
    	rgb_match = filename

    if labels_pattern.search(filename) is not None:
    	print "found labels match"
    	labels_match = filename

    if rgb_match.split("_")[0] == labels_match.split("_")[0]:
    	rgb_split = rgb_match.split("_")
    	if len(rgb_split)>1 and rgb_split[1] == "rgb.png":
    		print "found a pair"
    		WritePairToFile(rgb_match, labels_match)
    		rgb_match = ""
    		labels_match = ""
    
target.close()