# This script reads all of the files in ./train/
# that are saved in our CORL17 format
# and outputs a file that lists all files formatted
# for SegNet
#
###  Input: a subdirectory ./train/ with *rgb.png and *labels.png files (generated by preceding CORL17 pipeline)
###  Output: a .txt that lists of all *.rgb and *.labels pairs (for SegNet training)

import os
import re

print "Opening the training set descriptor file..."
target = open("train.txt", 'w')

rgb_pattern = re.compile("rgb")
labels_pattern = re.compile("labels")

cwd = os.getcwd()

rgb_match = ""
labels_match = ""


def WritePairToFile(rgb_file_name, labels_file_name):
	target.write(rgb_file_name)
	target.write(" ")
	target.write(labels_file_name)
	target.write("\n")
 
path_to_train = cwd + "/train"
for root, dirs, files in os.walk(path_to_train):
    for filename in sorted(files):
        filename_full_path = os.path.join(root, filename)
        print filename_full_path
        
        if rgb_pattern.search(filename_full_path) is not None:
    	    print "found rgb match"
    	    rgb_match = filename_full_path

        if labels_pattern.search(filename_full_path) is not None:
    	    print "found labels match"
    	    labels_match = filename_full_path

        if rgb_match.split("_")[0] == labels_match.split("_")[0]:
    	    rgb_split = rgb_match.split("_")
    	    if len(rgb_split)>1 and rgb_split[1] == "rgb.png":
                print "found a pair"
    	        WritePairToFile(rgb_match, labels_match)
    	        rgb_match = ""
    	        labels_match = ""
    
target.close()
